# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            # name='Greeting',
            # fields=[
            #     ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #     ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            # name='Station_record',
            # fields=[
            #     ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #     ('station_id', models.IntegerField()),
            #     ('name', models.CharField(max_length=100)),
            #     ('time_scrap', models.DateTimeField()),
            #     ('bikes_total', models.IntegerField()),
            #     ('bikes_available',models.IntegerField()),
            #     ('last_seen', models.DateTimeField()),
            #     ('anchorsb', JSONField()),
            # ],
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_scrape', models.DateTimeField()),
                ('feature_collection', JSONField()),
            ],
        ),
    ]
